#!/usr/bin/python
import random

numbs = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#random.shuffle(numbs)
#print(numbs)
mixed = []
while len(numbs) > 0 :
    index = random.randrange(len(numbs))
    mixed.append(numbs[index])
    numbs.remove(numbs[index])

print(mixed)